### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble.io#101]
Add a section/page to assemble.io where users can search for helpers, boilerplates and middleware for Assemble.

Basically what I have in mind is something like these:

* http://gulpjs.com/plugins/
* http://gruntjs.com/plugins
* http://yeoman.io/community-generators.html
* http://component.io/

Anyone interested in tackling this?!

**Comment by pburtchaell** [comment]
@bendrucker @jonschlinkert @doowb Is there still interest in having search on the site?

**Comment by jonschlinkert** [comment]
let's close for now

On Mon, Feb 23, 2015 at 1:57 PM, Patrick Burtchaell <
notifications@github.com> wrote:

> @bendrucker <https://github.com/bendrucker> @jonschlinkert
> <https://github.com/jonschlinkert> @doowb <https://github.com/doowb> Is
> there still interest in having search on the site?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assemble/assemble.io/issues/101#issuecomment-75607158>
> .
>



-- 

Jon Schlinkert
Core Team, LESS/Less.js
CEO, Sellside, Inc.
(513) 616-4335

github.com/jonschlinkert
linkedin.com/in/jonschlinkert <http://www.linkedin.com/in/jonschlinkert>
twitter.com/jonschlinkert <http://www.twitter.com/jonschlinkert>
