### ISSUE TITLE
Menubar still not Responsive

### ISSUE THREAD

**Issue by thenoelforte** [assemble/assemble.io#117]
I'm opening this as a continuation of #1; it would be really awesome if I could browse the assemble.io site on mobile, but can't due to the fact that the menu isn't auto-collapsing. Not sure if this is still in the works or not to fix, but I'd be happy to take a look at it if I knew where to look— still getting started with Grunt and all that.

**Comment by pburtchaell** [comment]
We are aware of the bug. This will soon be fixed in the v0.3.0 release.
