### ISSUE TITLE
Updating handlebars dependency to 2.0.0

### ISSUE THREAD

**Issue by Nooshu** [assemble/assemble.io#120]
Hello,

Hopefully someone can help. I really need to use {{@root}} in a couple of each loops, which has been added to version 2.0.0 according to this [post](https://github.com/wycats/handlebars.js/pull/392), but looking at the dependencies version 1.3.0 is currently being installed and used.

Is there any way to force assemble to use version 2.0.0?

I tried [this method](http://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) but had no luck. Any help would be greatly appreciated.

Thanks.

**Comment by jfrantzius** [comment]
Hi @doowb 
thanks for the workaround. Unfortunately it doesn't seem to survive an `rm -rf node_modules`, so one has to check in node_modules into source control (or at least `node_modules/assemble/node_modules/assemble-handlebars/`).

**Comment by doowb** [comment]
Sounds like that would be an issue with the `npm shrinkwrap --dev` command or `npm install` not respecting the shrinkwrap package.

In any case, Handlebars has been updated in `grunt-assemble` so if you're still using `assemble@0.4.x` you should start using `grunt-assemble` (or try out the latest assemble directly).

**Comment by jfrantzius** [comment]
Thx @doowb it seems that using grunt-assemble solves the problem, and I even managed to produce the right magical incantations in Gruntfile.js and package.json :)
