### ISSUE TITLE
Custom Helpers on Windows

### ISSUE THREAD

**Issue by dnh452** [assemble/assemble.io#136]
Following the documentation, no matter where I install grunt-init, and grunt-init-helper, I always get the error: 
"Local Npm module "grunt-init-helper" not found. Is it installed?" 

I have installed these both locally and globally and every time I fire up grunt I get that same warning. Is there documentation missing for Windows (8.1+) users?

**Comment by pburtchaell** [comment]
grunt-init is a tool that has been depreciated. Use [generator-helper](https://github.com/assemble/generator-helper) with [Yeoman](http://yeoman.io/) instead.
