### ISSUE TITLE
is 'content' a reserved variable?

### ISSUE THREAD

**Issue by goodpixels** [assemble/assemble.io#140]
so this doesn't work:

```
---
title: Home
content: 'Some text.'
---
{{content}}
```

but this works:

```
---
title: Home
my_content: 'Some text.'
---
{{my_content}}
```

is this intended? and why does this happen?

**Comment by jonschlinkert** [comment]
Is this related to Assemble or assemble.io? If assemble, can you create the issue on that repo?

**Comment by goodpixels** [comment]
hi Jon - sorry, I had both pages open and didn't realise I'm posing in the wrong one! feel free to close this one down, as I've just re-created this here: https://github.com/assemble/assemble/issues/649
