### ISSUE TITLE
middleware for layouts 

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble.io#142]
@doowb, do you think we might be able to move layout handling into a middleware? seems like a good use case.

**Comment by doowb** [comment]
Maybe... I had thought of that before but if another `preRender` middleware wants to change the page's `layout` property on `file.data` then we need to handle that after the middleware ran. Maybe we need to have a way to run middleware at a specific stage after all other middleware at that stage has run.

**Comment by jonschlinkert** [comment]
> Maybe we need to have a way to run middleware at a specific stage after all other middleware at that stage has run.

Instead of adding additional methods, like `last` or `first`, to have a middleware run after all other middleware in a stage, maybe we can take a done function or something, with behavior like the flush function in plugins

**Comment by jonschlinkert** [comment]
sorry let's move this to assemble.
