### ISSUE TITLE
ajax and handlebars.

### ISSUE THREAD

**Issue by harish2rock** [assemble/assemble.io#146]
I have an ajax call in my js file. How do I pass the response of this ajax call to an handlebars template ?
Something like this -
	var raw_template = $('#simple-template').html();
	var template = Handlebars.compile(raw_template);
		$.getJSON("/restful/fortune", function(response) {
			var html = template(response);
			$('#main').append(html);
		});

The handlebars template is defined in a hbs file (another handlebars file 'results.hbs') as -
<script id="simple-template" type="text/x-handlebars-template">
<div id="main">
<p>{{response.status}}</p>
<p>{{response.fortune}}</p>
</div>
</script>

Assemble is parsing the handlebars template as html itself. Can you please help me out ?

**Comment by jpgcode** [comment]
I'm not sure if I'm wrong, but as far I know Assemble works with pre-compiled templates, this means that it works precompiling the files and serving the result to the browser as standard HTML. If you want to pull content from a REST API and then process the templates each time the your page loads, you will need to do it with handlebars runtime script, here an example of how to do it: [https://github.com/jpgcode/handlebars-json-example](https://github.com/jpgcode/handlebars-json-example)

**Comment by jonschlinkert** [comment]
closing since this is probably a better question/discussion for stackoverflow.
