### ISSUE TITLE
handlebars does not support render

### ISSUE THREAD

**Issue by eurolife** [assemble/assemble.io#158]
I am trying to run assemble and have set it up according to instructions and examples but always get this error: Running "assemble:pages" (assemble) task
handlebars does not support render.
Assembling app/pages/default.html ERROR
Warning: handlebars does not support render. Use --force to continue.

I've searched high and low for a solution and have only found a couple others with this same issue but no responses or suggestions as to what to do. Can someone suggest something please?

**Comment by jonschlinkert** [comment]
Hmm, I was going to move the issue over to the handlebars-helpers lib, but I'm not sure if that's related. What version of assemble are you using? Any other details you can share would be great.

**Comment by eurolife** [comment]
Looks like it is v 0.4.42. I'm also running it in a customized version of yo-webapp. So this is happening when I run grunt server or simply grunt assemble. This is what I have added into the grunt file:

// assemble 
    assemble: {
      options: {
            flatten:true,
            partials: ['<%= config.app %>/html/partials/**/*.hbs'],
            layout: ['<%= config.app %>/html/default.hbs'],
            data: ['<%= config.app %>/html/data/*.{json,yml}']
        },
        pages: {
            files: {
                // Assemble from temp into dist
                '<%= config.app  %>/pages': ['<%= config.app  %>/html/*.hbs']
            }
        }
    },

**Comment by jonschlinkert** [comment]
k, it seems it's effecting grunt-assemble users. I'm closing here to move the discussion to the linked issue on grunt-assemble

**Comment by jonschlinkert** [comment]
thanks for the addl info
