### ISSUE TITLE
withSort not working for pages collection

### ISSUE THREAD

**Issue by toby1kenobi** [assemble/assemble.io#50]
The final section [here](http://assemble.io/docs/Pages-Collections.html) talks about sorting the pages collection:

```
<ul>
    {{#withSort pages data.date}}
        <li>{{data.title}}</li>
    {{/withSort}}
</ul>
```

If I add that code to a page within the boilerplate-bootstrap project, for example, the build fails with 

```
Warning: Cannot read property 'hash' of undefined Use --force to continue
Aborted due to warnings.
```

This will build

```
    {{#withSort pages date}}
```

But the output is not sorted.

Am I missing something, should this work?

**Comment by webercoder** [comment]
@mattdwen @mayhemchaos I know it's been a while, but I suppose for people in the future who have arrived here like me...

Handlebars helpers can take extra arguments (specified by name) after the default ones are provided. For more info on that, search for `options.hash` on this page: http://handlebarsjs.com/expressions.html

The `withSort` helper that the assemble.io guys wrote does this as well.  If you provide `dir="desc"` after your arguments, the loop's array will be reversed and you'll be good to go!

    {{#withSort pages "data.created" dir="desc" }}
        {{#unless data.exclude}}
            <li><a href="{{getPostUrl data.post_name data.created}}">{{data.title}}</a></li>
          {{/unless}}
    {{/withSort}}

Here is the code that does it:
https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-collections.js#L279

**Comment by pacav69** [comment]
Refer to my 'Tip: Using the #withSort in handlebars

Vhttps://github.com/assemble/handlebars-helpers/issues/200

**Comment by satuweb** [comment]
@webercoder Great!
